# Generated by Django 2.2 on 2019-05-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subnets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('ip', models.TextField(blank=True)),
                ('allowed_subnets', models.ManyToManyField(to='myapp.Allowed')),
            ],
        ),
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_Name', models.TextField(blank=True)),
                ('rows', models.ManyToManyField(to='myapp.Subnets')),
            ],
        ),
    ]
